gui:
  language: 'en'
  mouseEvents: false
  sidePanelWidth: 0.333
  mainPanelSplitMode: 'horizontal' # one of 'horizontal' | 'flexible' | 'vertical'
  showFileTree: false # ` to toggle
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} {{filename}}'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  disableForcePushing: true
promptToReturnFromSubprocess: false
