# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[->](green)"     # The "symbol" segment is being set to "➜"
error_symbol = "[!->](bold red)"     # The "symbol" segment is being set to "➜"
vicmd_symbol = "[V](bold green)"
