alias ta='tmux attach-session -d -t'
alias tl='tmux list-sessions'
alias tc='tmux'
alias ls='eza'
#alias vim='nvim'
alias irssi='TERM=screen-256color irssi'
alias emacs="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"
alias make="ponymake"
alias yarn="ponyyarn"
alias fly="ponyfly"
alias pnpm="ponypnpm"
alias now="ponyyarn run now"
#alias elm="ponyyarn run elm"
#alias watch="ponyyarn run watch"
alias cargo="ponycargo"
alias podman="ponypodman"
alias bloop="ponybloop"
alias cmake="ponycmake"
alias invoke="ponyinvoke"
alias lipass="PASSWORD_STORE_DIR=~/personal-repos/lichess/sysadmin/pass pass"
alias kssh="kitty +kitten ssh"
alias lg="lazygit"
alias cat="bat"
alias gd="git diff"
alias gs="git status"
alias gm="git mergetool"
alias stpub="pushd ~/work-repos/playstrategy/strategygames && sbt publishLocal; popd"
alias sttest="pushd ~/work-repos/playstrategy/strategygames && sbt testOnly; popd"
